[package]
name = "alive"
version = "0.3.1"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
inquisitor_lib = {path="../../../inquisitor_lib"}
serde = "1.0.37"
serde_derive = "1.0.37"
