[package]
name = "system_monitor"
version = "0.3.1"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
inquisitor_lib = {path="../../../inquisitor_lib"}
serde_json = "1.0.13"
sysinfo = "0.5.4"
serde_derive = "1.0.37"
serde = "1.0.37"
