[package]
name = "Inquisitor server"
version = "0.2.0"
authors = ["George Hosu <george@cerebralab.com>"]
build = "build.rs"

[dependencies]
rusqlite = "0.13.0"

tokio-core = "0.1.15"
tokio = "0.1.3"
futures = "0.1.18"
time = "0.1.39"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

yaml-rust = "0.4"

url="1.7.0"

fs_extra = "1.1.0"

walkdir = "2"

hyper = "0.11"
hyper-staticfile = "0.1.1"

[features]
default = []

[[bin]]
name = "inquisitor_receptor"
path = "receptor_processed.rs"

[build-dependencies]
fs_extra = "1.1.0"
