[package]
name = "Inquisitor server"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
tokio-core = "0.1.15"
tokio = "0.1.3"
futures = "0.1.18"
time = "0.1.39"

hyper = "0.11"
hyper-staticfile = "0.1.1"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
yaml-rust = "0.4"

fs_extra = "1.1.0"
walkdir = "2"


receptor_lib = {path="receptor_lib"}
plugins = {path="plugins"}
shared_lib = {path="../shared_lib"}

[dependencies.rusqlite]
version = "0.11.0"
features = ["bundled"]

[[bin]]
name="inquisitor_receptor"
path="src/main.rs"

[workspace]
