[package]
name = "agent_lib"
version = "0.2.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
fs_extra = "1.1.0"
# Required for plugin, maybe move somewhere else
sysinfo = "0.5.1"

yaml-rust = "0.4"