[package]
name = "agent_lib"
version = "0.3.0"
authors = ["Richard Petrie <rap1011@ksu.edu>"]

[dependencies]
fs_extra = "1.1.0"
sysinfo = "0.5.4"
yaml-rust = "0.4.0"
shared_lib = {path="../../shared_lib"}
