[package]
name = "file_checker"
version = "0.3.1"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
serde_json = "1.0.13"
serde = "1.0.37"
serde_derive = "1.0.37"
fs_extra = "1.1.0"
inquisitor_lib = {path="../../../inquisitor_lib"}
