[package]
name = "file_checker"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
fs_extra = "1.1.0"
agent_lib = {path="../../agent_lib"}
