[package]
name = "inquisitor_agent_file_checker"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
serde_json = "1.0.16"
serde = "1.0.43"
serde_derive = "1.0.43"
fs_extra = "1.1.0"
inquisitor_lib = {path="../../../inquisitor_lib"}
