[package]
name = "process_counter"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
agent_lib = {path="../../agent_lib"}
serde_json = "1.0.13"
serde = "1.0.37"
serde_derive = "1.0.37"
