[package]
name = "Inquisitor agent"
version = "0.1.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
hyper = "0.11"
tokio-core = "0.1.15"
futures = "0.1.18"
hyper-tls = "0.1.3"

[features]
default = []

[[bin]]
name = "endpoint"
path = "main.rs"
