[package]
name = "shared_lib"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
fs_extra = "1.1.0"
yaml-rust = "0.4"
url="1.7.0"
