[package]
name = "inquisitor_agent"
version = "0.2.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1.3"
futures = "0.1.18"

hostname = "^0.1"
agent_lib = {path="agent_lib"}
plugins = {path="plugins"}
