[package]
name = "inquisitor_agent"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
tokio = "0.1.3"
futures = "0.1.18"
log = "0.4.0"
env_logger = "0.5.6"
hostname = "^0.1"

agent_lib = {path="agent_lib"}
plugins = {path="plugins"}

[workspace]
