[package]
name = "sync_check"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
receptor_lib = {path="../../receptor_lib"}
serde_json = "1.0"

[dependencies.rusqlite]
version = "0.11.0"
features = ["bundled"]
